XNP_PZ_DistanceRunner = XNP_PZ_DistanceRunner or {}

local Core = XNP_PZ_DistanceRunner

local Constants = {
    MOD_NAME = "XNP Distance Runner Trait 0.5.60.6.11 Red Item Use Release Workshop RC4",
    MOD_ID = "XNP_PZ_DistanceRunnerTrait",
    VERSION = "0.5.60.6.11",
    INTERNAL_VERSION = "0.5.60.6.11-b42-red-item-use-release-workshop-rc4-a",
    BUILD_ID = "XNP_PZ_DISTANCE_TRAIT_0560611_RED_ITEM_USE_RELEASE_WORKSHOP_RC4_A",
    RELEASE_CHANNEL = "WORKSHOP_RC4",
    WORKSHOP_UPLOAD_STATUS = "PREPARED_NOT_UPLOADED",
    AUTHOR = "XN-PHL",
    LOG_PREFIX = "[XNP DistanceRunner]",

    TRAIT_ID = "XNPDistanceRunner",
    TRAIT_MODULE = "XNPDistanceRunnerTrait",
    TRAIT_FULL_ID = "XNPDistanceRunnerTrait:XNPDistanceRunner",
    TRAIT_DISPLAY_NAME_CN = "UI_trait_XNPDistanceRunner",
    TRAIT_DISPLAY_NAME_EN = "Distance Runner",
    TRAIT_DEFINITION_METHOD = "RESTORED_NATIVE_CHARACTER_TRAIT",
    TRAIT_DETECTION_METHOD = "RESTORED_OBJECT_TRAIT_DETECTOR",
    TRAIT_COST = 1,

    STAMINA_DRAIN_METHOD = "POST_DRAIN_REFUND_BY_ENDURANCE_BAND",
    ADRENALINE_TRIGGER_METHOD = "CENTRAL_WORLD_QUERY_LIVE_ZOMBIE_DISTANCE",
    METABOLIC_COST_METHOD = "TIERED_FOOD_RECOVERY_SINGLE_WRITER",
    METABOLIC_APPLICATION_STATUS = "AUTHORITY_ONLY_TIERED_PULSE",
    MELEE_BONUS_METHOD = "EVENT_DRIVEN_HIGH_ENDURANCE_ZOMBIE_ONLY_DAMAGE_BONUS",
    SANDBOX_OPTIONS_METHOD = "NATIVE_SANDBOX_OPTIONS_SERVER_AUTHORITATIVE",
    STATUS_MOODLE_METHOD = "DEFERRED_NOT_ABANDONED",
    STATUS_ICON_FALLBACK = "DISABLED_BY_DEFAULT",
    MOVEMENT_SPEED_MODIFICATION_METHOD = "NONE",
    RUNNING_SHOVE_STATUS = "DISABLED",
    PLAYER_COLLISION_STATE_STATUS = "DISABLED",
    SHOULDER_CHECK_METHOD = "BREAKOUT_PUSH",
    SHOULDER_IMPACT_METHOD = "REPLACED_BY_BREAKOUT_PUSH",
    SHOULDER_IMPACT_AUDIT_RESULT = "PRECOLLISION_BREAKOUT_REPLACES_PLAYER_SIDE_COLLISION_CHAIN",
    BREAKOUT_PUSH_METHOD = "FULL_SPRINT_IMMUNITY_STRICT_CONTACT",
    BREAKOUT_TRIGGER_MODE = "PRECOLLISION_OR_GRAB_TRIGGER",
    VISUAL_FEEDBACK_METHOD = "DEFERRED_NOT_ABANDONED",
    VISUAL_FEEDBACK_TEXT_LANGUAGE = "DISABLED",
    STAMINA_SUMMARY_LOG_INTERVAL = 10.0,
    RIGHT_TOP_ICON_STATUS = "FOUR_INDEPENDENT_EVIDENCE_BASED_ROUND_STATUS_PANELS",
    ICON_FEATURE_STATUS = "DEFERRED_NOT_ABANDONED",
    ICON_RED_FLASH_STATUS = "REMOVED_WITH_OLD_FOUR_ICON_TEMPLATE",
    MOODLE_FEATURE_STATUS = "DEFERRED_NOT_ABANDONED",
    HALO_TEXT_STATUS = "FAILED_ROUTE_NOT_CURRENT_TARGET",
    COORDINATE_ICON_STATUS = "FAILED_ROUTE_NOT_CURRENT_TARGET",
    PLAYER_SAY_STATUS = "FORBIDDEN",
    TEXT_FALLBACK_STATUS = "DEBUG_ONLY_NOT_MAIN_UI",
    BALANCE_STATUS = "LOCAL_PERFORMANCE_FOOD_MELEE_TEST",
    COLOR_SOURCE = "ENDURANCE_VALUE_ONLY",
    ACTIVATION_STATUS = "FIRST_CLASS_BLOCKER",
    SPRINT_STATUS = "VEHICLE_IMPACT_0_3_SECOND_QUOTA_WALL_CRASH",
    WALK_STATUS = "NO_ACTIVE_IMPACT",
    JOG_STATUS = "PRESERVED_WHEN_JOGGING",
    CONTROLLED_ESCAPE_STATUS = "PRESERVED_RUN_OR_SPRINT_INPUT_REQUIRED",
    GRAB_ESCAPE_STATUS = "PRESERVED",
    SKILL_ACTIVE_QUOTA_STATUS = "RUNTIME_INTEGRATED",
    DIRECT_DRAG_STATUS = "NO_MODIFIER_ABSOLUTE_OR_DELTA_COORDS",
    FALL_RECOVERY_STATUS = "LOCAL_RADIUS_LOCKED",
    RADIUS_STATUS = "EFFECT_RADIUS_REDUCED",
    NO_BITE_NO_INFECTION_NO_HEAL = "PRESERVED",
    ICON_DRAG_STATUS = "SHARED_B42_CAPTURE_MOVE_OUTSIDE_UP_OUTSIDE",
    ICON_TOOLTIP_STATUS = "CN_EN_HOVER_TOOLTIP_MASTER_TOGGLE",
    SPRINT_WALL_STATUS = "NATIVE_TRIP_WINDOW_NOT_FORCED_WALL_CRASH",
    SPRINT_TRIP_CONSEQUENCE = "KILL_MAX_3_REST_KNOCKDOWN_STUN_MINOR_SCRAPE",
    BODY_STATUS_APPLICATION_METHOD = "DISABLED_AUDIT_ONLY",
    STATUS_ICON_LAYOUT_METHOD = "FOUR_NEW_0557_POSITION_KEYS_WITH_READ_ONLY_LEGACY_MIGRATION",
    STATUS_ICON_RENDER_METHOD = "NATIVE_MOODLE_ROUND_SHELL_WITH_FOUR_LOCKED_UNTINTED_CENTERS",
    TRAIT_ICON = "media/ui/Traits/trait_xnpdistancerunner.png",
    GREEN_ORB_WORLD_VISUAL_METHOD = "DISABLED_FOR_RENDER_SAFETY",
    GREEN_ORB_IMPACT_PRIMARY_METHOD = "PURE_LUA_WORLD_COORDINATE_TRANSACTION",
    GREEN_ORB_IMPACT_FALLBACK_METHOD = "LOCAL_BLAST_ZOMBIE_ONLY",
    GREEN_ORB_RUNTIME_VISUAL_STATUS = "ENTITY_RENDERING_FORCED_OFF",
}

Constants.FEATURE = {
    ADRENALINE = true,
    STAMINA_DRAIN = true,
}

Constants.ADRENALINE = {
    THREAT_TRIGGER_RADIUS = 4.00,
    THREAT_SCAN_INTERVAL = 0.50,
    ACTIVE_REFRESH = 8.00,
    MEMORY_DURATION = 20.00,
    SAME_Z_TOLERANCE = 0.50,
}

function Constants.IsFiniteNumber(value)
    return type(value) == "number" and value == value and value ~= math.huge and value ~= -math.huge
end

function Constants.Clamp(value, min_value, max_value)
    if not Constants.IsFiniteNumber(value) then
        return min_value
    end
    if value < min_value then
        return min_value
    end
    if value > max_value then
        return max_value
    end
    return value
end

function Constants.Log(message)
    print(Constants.LOG_PREFIX .. " " .. tostring(message))
end

if not Core.constants_0560611_startup_logged then
    Core.constants_0560611_startup_logged = true
    print("[XNP 0.5.60.6.11 STARTUP] constants_loaded=true")
end

Core.Constants = Constants
return Constants

