XNP_PZ_DistanceRunner = XNP_PZ_DistanceRunner or {}

local Schema = {
    namespace = "XNPDistanceRunner",
    specs = {
        EnableMod = { kind = "boolean", fallback = true },
        TuningPreset = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        EnableDebugSummary = { kind = "boolean", fallback = false },
        LiveRefreshTuning = { kind = "boolean", fallback = true },
        GlobalSkillCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        ZombieImpactCostMultiplier = { kind = "number", fallback = 0.24, min = 0.00, max = 2.00 },
        JogBumpCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        SprintPrecollisionCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        SprintVehicleZombieCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        ControlledEscapeCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        NativeTripCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        StaminaAssistIntensity = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        BlueRefundPercent = { kind = "number", fallback = 30, min = 0, max = 90, integer = true },
        YellowRefundPercent = { kind = "number", fallback = 38, min = 0, max = 90, integer = true },
        RedRefundPercent = { kind = "number", fallback = 55, min = 0, max = 90, integer = true },
        ExtraHungerCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 3.00 },
        ResourceGateEnabled = { kind = "boolean", fallback = true },
        GreenExitPercent = { kind = "number", fallback = 70, min = 40, max = 95, integer = true },
        GreenEnterPercent = { kind = "number", fallback = 76, min = 45, max = 100, integer = true },
        BlueLowerPercent = { kind = "number", fallback = 36, min = 10, max = 80, integer = true },
        YellowLowerPercent = { kind = "number", fallback = 14, min = 1, max = 60, integer = true },
        ShowStatusIcon = { kind = "boolean", fallback = true },
        EnableStatusShake = { kind = "boolean", fallback = true },
        PerformanceMode = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        IdleThreatScanMs = { kind = "number", fallback = 500, min = 100, max = 2000, integer = true },
        ActiveThreatScanMs = { kind = "number", fallback = 100, min = 50, max = 1000, integer = true },
        CriticalThreatScanMs = { kind = "number", fallback = 50, min = 25, max = 500, integer = true },
        MaxNearbyCandidates = { kind = "number", fallback = 16, min = 4, max = 16, integer = true },
        EnableRuntimeDebug = { kind = "boolean", fallback = false },
        EnableLowEnduranceFoodConversion = { kind = "boolean", fallback = true },
        EnableTieredFoodRecovery = { kind = "boolean", fallback = true },
        FoodRecoveryPulseSeconds = { kind = "number", fallback = 2.00, min = 0.50, max = 10.00 },
        BlueFoodCostPercent = { kind = "number", fallback = 0.50, min = 0.00, max = 10.00 },
        BlueEnduranceGainPercent = { kind = "number", fallback = 1.50, min = 0.01, max = 20.00 },
        YellowRedFoodCostPercent = { kind = "number", fallback = 1.00, min = 0.00, max = 10.00 },
        YellowRedEnduranceGainPercent = { kind = "number", fallback = 2.00, min = 0.01, max = 20.00 },
        FoodConversionTriggerPercent = { kind = "number", fallback = 30, min = 5, max = 95, integer = true },
        FoodConversionTargetPercent = { kind = "number", fallback = 40, min = 5, max = 95, integer = true },
        MinimumFoodReservePercent = { kind = "number", fallback = 40, min = 40, max = 95, integer = true },
        FoodToEnduranceRatioPercent = { kind = "number", fallback = 100, min = 25, max = 400, integer = true },
        FoodConversionRatePercentPerSecond = { kind = "number", fallback = 1, min = 1, max = 10, integer = true },
        EnableHighEnduranceMeleePower = { kind = "boolean", fallback = true },
        MeleePowerStartEndurancePercent = { kind = "number", fallback = 80, min = 1, max = 100, integer = true },
        MeleePowerFullEndurancePercent = { kind = "number", fallback = 95, min = 1, max = 100, integer = true },
        MeleePowerMaxMultiplier = { kind = "number", fallback = 2.00, min = 1.00, max = 2.00 },
        EnablePhoenixTraitLogic = { kind = "boolean", fallback = true },
        PhoenixTraitPointCost = { kind = "number", fallback = 1, min = 1, max = 20, integer = true },
        PhoenixTriggerHealthPercent = { kind = "number", fallback = 20, min = 20, max = 20, integer = true },
        PhoenixInvulnerabilitySeconds = { kind = "number", fallback = 0.00, min = 0.00, max = 10.00 },
        PhoenixBaseCooldownDays = { kind = "number", fallback = 7, min = 1, max = 30, integer = true },
        PhoenixRequirePanicZeroToRecharge = { kind = "boolean", fallback = true },
        PhoenixPanicZeroThreshold = { kind = "number", fallback = 0, min = 0, max = 100, integer = true },
        PhoenixEarlyRechargeEnabled = { kind = "boolean", fallback = true },
        PhoenixEarlyRechargeMaxDays = { kind = "number", fallback = 2, min = 0, max = 6, integer = true },
        PhoenixMinimumCooldownDays = { kind = "number", fallback = 5, min = 1, max = 30, integer = true },
        PhoenixWellFedCreditMaxDays = { kind = "number", fallback = 1, min = 0, max = 6, integer = true },
        PhoenixHealthyCreditMaxDays = { kind = "number", fallback = 1, min = 0, max = 6, integer = true },
        PhoenixWellFedRequiredGameHours = { kind = "number", fallback = 24, min = 1, max = 720, integer = true },
        PhoenixHealthyRequiredGameHours = { kind = "number", fallback = 24, min = 1, max = 720, integer = true },
        PhoenixHealthyMinHealthPercent = { kind = "number", fallback = 95, min = 50, max = 100, integer = true },
        PhoenixProtectRadius = { kind = "number", fallback = 2.00, min = 1.00, max = 3.50 },
        PhoenixRestoreEndurancePercent = { kind = "number", fallback = 100, min = 25, max = 100, integer = true },
        PhoenixFullCureToggle = { kind = "boolean", fallback = true },
        PhoenixClearZombification = { kind = "boolean", fallback = true },
        PhoenixProtectDurationSeconds = { kind = "number", fallback = 0.00, min = 0.00, max = 5.00 },
        PhoenixShowStatusIcon = { kind = "boolean", fallback = true },
        PhoenixTooltipEnable = { kind = "boolean", fallback = true },
        PhoenixIconShakeDuringInvulnerability = { kind = "boolean", fallback = true },
        Preset = { kind = "number", fallback = 1, min = 1, max = 5, integer = true },
        EnableYellowTraitSystem = { kind = "boolean", fallback = true },
        EnablePurplePhoenixSystem = { kind = "boolean", fallback = true },
        EnableGreenTraitSystem = { kind = "boolean", fallback = true },
        EnableRedTraitSystem = { kind = "boolean", fallback = true },
        EnableRoundMarkers = { kind = "boolean", fallback = true },
        EnableTooltips = { kind = "boolean", fallback = true },
        EnableSounds = { kind = "boolean", fallback = true },
        HideMarkersWithMap = { kind = "boolean", fallback = true },
        DiagnosticLogLevel = { kind = "number", fallback = 2, min = 1, max = 4, integer = true },
        MultiplayerAuthorityMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        YellowEnableDistanceGrowth = { kind = "boolean", fallback = true },
        YellowSpeedGrowthRate = { kind = "number", fallback = 0.02, min = 0, max = 0.2 },
        YellowMaxSpeedMultiplier = { kind = "number", fallback = 1.4, min = 1, max = 3 },
        YellowDistanceDecayDelay = { kind = "number", fallback = 2, min = 0, max = 30 },
        YellowDistanceDecayRate = { kind = "number", fallback = 0.05, min = 0, max = 1 },
        YellowJogBumpEnabled = { kind = "boolean", fallback = true },
        YellowSprintImpactEnabled = { kind = "boolean", fallback = true },
        YellowSprintTripImmunityEnabled = { kind = "boolean", fallback = true },
        YellowGrabBreakoutEnabled = { kind = "boolean", fallback = true },
        YellowEmergencyGetupEnabled = { kind = "boolean", fallback = true },
        YellowContactEnduranceCost = { kind = "number", fallback = 0.025, min = 0, max = 0.5 },
        YellowGrabEnduranceCost = { kind = "number", fallback = 0.06, min = 0, max = 0.75 },
        YellowLowEnduranceInjuryRisk = { kind = "number", fallback = 0.15, min = 0, max = 1 },
        YellowMarkerShakeEnabled = { kind = "boolean", fallback = true },
        YellowMarkerShakeIntensity = { kind = "number", fallback = 1, min = 0, max = 3 },
        PurpleEnabled = { kind = "boolean", fallback = true },
        PurpleTriggerHealthPercent = { kind = "number", fallback = 20, min = 1, max = 50, integer = true },
        PurpleCooldownMode = { kind = "number", fallback = 1, min = 1, max = 1, integer = true },
        PurpleCooldownRealSeconds = { kind = "number", fallback = 3, min = 1, max = 300 },
        PurpleRecoveryHealthPercent = { kind = "number", fallback = 100, min = 1, max = 100, integer = true },
        PurpleRecoveryEndurancePercent = { kind = "number", fallback = 100, min = 1, max = 100, integer = true },
        PurpleFallProtectionEnabled = { kind = "boolean", fallback = true },
        PurpleRangedPredeathProtectionEnabled = { kind = "boolean", fallback = true },
        PurplePanicGateEnabled = { kind = "boolean", fallback = true },
        PurpleManualToggleEnabled = { kind = "boolean", fallback = true },
        PurpleCooldownReadyState = { kind = "number", fallback = 1, min = 1, max = 5, integer = true },
        PurpleDiagnosticDeathLogEnabled = { kind = "boolean", fallback = false },
        GreenMeleeEnabledByDefault = { kind = "boolean", fallback = true },
        GreenHighTierEndurancePercent = { kind = "number", fallback = 80, min = 1, max = 100, integer = true },
        GreenMidTierEndurancePercent = { kind = "number", fallback = 40, min = 1, max = 100, integer = true },
        GreenHighTierDamageMultiplier = { kind = "number", fallback = 8, min = 1, max = 20 },
        GreenMidTierDamageMultiplier = { kind = "number", fallback = 5, min = 1, max = 20 },
        GreenLowTierDamageMultiplier = { kind = "number", fallback = 2.5, min = 1, max = 20 },
        GreenHighTierEnduranceCost = { kind = "number", fallback = 3, min = 0, max = 25 },
        GreenMidTierEnduranceCost = { kind = "number", fallback = 2, min = 0, max = 25 },
        GreenLowTierEnduranceCost = { kind = "number", fallback = 1, min = 0, max = 25 },
        GreenStructureDamageMultiplier = { kind = "number", fallback = 20, min = 1, max = 50 },
        GreenMissCostsEndurance = { kind = "boolean", fallback = false },
        GreenActiveSkillEnabled = { kind = "boolean", fallback = true },
        GreenActiveMode = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        GreenCooldownRealSeconds = { kind = "number", fallback = 5, min = 0.5, max = 120 },
        GreenTargetSearchRadiusTiles = { kind = "number", fallback = 12, min = 1, max = 30 },
        GreenNoTargetSearchSeconds = { kind = "number", fallback = 3.0, min = 0.1, max = 10 },
        GreenImpactVisualHoldMs = { kind = "number", fallback = 300, min = 100, max = 1000, integer = true },
        GreenInitialSpeedMultiplier = { kind = "number", fallback = 1, min = 0.1, max = 5 },
        GreenAccelerationStartSeconds = { kind = "number", fallback = 3, min = 0, max = 10 },
        GreenAccelerationMultiplierPerSecond = { kind = "number", fallback = 1.5, min = 1, max = 3 },
        GreenMaximumVirtualSpeedTilesPerSecond = { kind = "number", fallback = 8, min = 0.5, max = 30 },
        GreenMaximumFlightSeconds = { kind = "number", fallback = 8, min = 0.5, max = 30 },
        GreenImpactDistanceTiles = { kind = "number", fallback = 0.55, min = 0.1, max = 2 },
        GreenExplosionRadiusTiles = { kind = "number", fallback = 7, min = 0.5, max = 15 },
        GreenExplosionBaseDamage = { kind = "number", fallback = 10, min = 0.1, max = 100 },
        GreenExplosionFalloffEnabled = { kind = "boolean", fallback = true },
        GreenTargetOutlineEnabled = { kind = "boolean", fallback = true },
        GreenLockAreaEnabled = { kind = "boolean", fallback = true },
        GreenLockAreaRadiusTiles = { kind = "number", fallback = 4, min = 1, max = 12 },
        GreenLockOutlinePulseEnabled = { kind = "boolean", fallback = true },
        GreenLockOutlinePulseIntervalSeconds = { kind = "number", fallback = 3, min = 0.5, max = 30 },
        GreenLockOutlinePulseDurationSeconds = { kind = "number", fallback = 0.65, min = 0.1, max = 5 },
        GreenBanditDamageEnabled = { kind = "boolean", fallback = true },
        GreenRuntimeTestNoCooldown = { kind = "boolean", fallback = true },
        GreenOrbScreenDiameterPx = { kind = "number", fallback = 36, min = 12, max = 128, integer = true },
        GreenOrbGlowDiameterPx = { kind = "number", fallback = 48, min = 16, max = 160, integer = true },
        GreenMinimumVisibleFlightMs = { kind = "number", fallback = 500, min = 100, max = 5000, integer = true },
        GreenMinimumInflightRenderFrames = { kind = "number", fallback = 2, min = 2, max = 30, integer = true },
        GreenInflightDiagnosticBorderEnabled = { kind = "boolean", fallback = true },
        GreenCastSoundEnabled = { kind = "boolean", fallback = true },
        GreenImpactSoundEnabled = { kind = "boolean", fallback = true },
        GreenRefundCooldownOnNoTarget = { kind = "boolean", fallback = true },
        GreenExperimentalEntityRendering = { kind = "boolean", fallback = false },
        GreenWhiteActionEnabled = { kind = "boolean", fallback = true },
        GreenWhiteActionDurationSeconds = { kind = "number", fallback = 4, min = 0.5, max = 30 },
        GreenWhiteHealthCost = { kind = "number", fallback = 0.05, min = 0, max = 0.5 },
        GreenWhiteEnduranceCost = { kind = "number", fallback = 0.15, min = 0, max = 1 },
        GreenWhiteUnhappinessCost = { kind = "number", fallback = 5, min = 0, max = 100 },
        GreenWhiteBoredomCost = { kind = "number", fallback = 5, min = 0, max = 100 },
        GreenWhiteMidActionSoundEnabled = { kind = "boolean", fallback = true },
        GreenWhiteActionResultMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        RedStarterItemCount = { kind = "number", fallback = 3, min = 0, max = 20, integer = true },
        RedCraftEnabled = { kind = "boolean", fallback = true },
        RedCraftDurationSeconds = { kind = "number", fallback = 4, min = 0.5, max = 60 },
        RedCraftHealthCost = { kind = "number", fallback = 0.05, min = 0, max = 0.5 },
        RedCraftHungerCost = { kind = "number", fallback = 0.1, min = 0, max = 1 },
        RedSafetyFloorPercent = { kind = "number", fallback = 20, min = 1, max = 95, integer = true },
        RedStaminaImmediateRecovery = { kind = "number", fallback = 0.5, min = 0, max = 1 },
        RedStaminaPeriodicRecovery = { kind = "number", fallback = 0.05, min = 0, max = 1 },
        RedStaminaPeriodicIntervalSeconds = { kind = "number", fallback = 2, min = 0.5, max = 60 },
        RedStaminaPeriodicDurationSeconds = { kind = "number", fallback = 20, min = 0, max = 300 },
        RedFatigueReduction = { kind = "number", fallback = 0.25, min = 0, max = 1 },
        RedMoodReductionPercent = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        RedHealingHealthAmount = { kind = "number", fallback = 25, min = 0, max = 100 },
        RedHealFractureEnabled = { kind = "boolean", fallback = true },
        RedClearZombieInfectionEnabled = { kind = "boolean", fallback = true },
        RedHealMinorWoundCount = { kind = "number", fallback = 3, min = 0, max = 20, integer = true },
        RedHealMajorWoundCount = { kind = "number", fallback = 1, min = 0, max = 20, integer = true },
        MarkerScale = { kind = "number", fallback = 1, min = 0.5, max = 2 },
        MarkerOpacity = { kind = "number", fallback = 1, min = 0.2, max = 1 },
        MarkerDragEnabled = { kind = "boolean", fallback = true },
        MarkerResetPositions = { kind = "boolean", fallback = false },
        TooltipDetailLevel = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        EnableTargetOutline = { kind = "boolean", fallback = true },
        PerformanceUpdateIntervalFrames = { kind = "number", fallback = 6, min = 1, max = 120, integer = true },
        EvidenceLogEnabled = { kind = "boolean", fallback = false },
        YellowDistanceGrowthRate = { kind = "number", fallback = 0.02, min = 0, max = 0.2 },
        YellowInitialSpeedMultiplier = { kind = "number", fallback = 1, min = 1, max = 3 },
        YellowMaximumSpeedMultiplier = { kind = "number", fallback = 1.4, min = 1, max = 3 },
        YellowDecayDelaySeconds = { kind = "number", fallback = 2, min = 0, max = 30 },
        YellowDecayRate = { kind = "number", fallback = 0.05, min = 0, max = 1 },
        YellowJogMinimumSpeed = { kind = "number", fallback = 1.45, min = 0.1, max = 5 },
        YellowJogImpactForce = { kind = "number", fallback = 1, min = 0, max = 3 },
        YellowJogStaggerChance = { kind = "number", fallback = 0.70, min = 0, max = 1 },
        YellowJogKnockdownChance = { kind = "number", fallback = 0.22, min = 0, max = 1 },
        YellowSprintMinimumSpeed = { kind = "number", fallback = 3.25, min = 0.1, max = 8 },
        YellowSprintImpactForce = { kind = "number", fallback = 1, min = 0, max = 3 },
        YellowSprintStaggerChance = { kind = "number", fallback = 1, min = 0, max = 1 },
        YellowSprintKnockdownChance = { kind = "number", fallback = 1, min = 0, max = 1 },
        YellowGrabBreakoutCooldownSeconds = { kind = "number", fallback = 3, min = 0.1, max = 30 },
        YellowEmergencyGetupCooldownSeconds = { kind = "number", fallback = 0.75, min = 0.1, max = 30 },
        YellowLowEnduranceInjuryChance = { kind = "number", fallback = 0.15, min = 0, max = 1 },
        PurpleBaseCooldownDays = { kind = "number", fallback = 7, min = 1, max = 30, integer = true },
        PurpleMinimumCooldownDays = { kind = "number", fallback = 5, min = 1, max = 30, integer = true },
        PurpleEarlyRecoveryMaximumDays = { kind = "number", fallback = 2, min = 0, max = 6, integer = true },
        PurpleInvulnerabilitySeconds = { kind = "number", fallback = 0, min = 0, max = 30 },
        PurpleMaximumTriggerCount = { kind = "number", fallback = 0, min = 0, max = 999, integer = true },
        GreenDisabledDamageMultiplier = { kind = "number", fallback = 1, min = 1, max = 20 },
        GreenCooldownSeconds = { kind = "number", fallback = 5, min = 0.5, max = 120 },
        GreenMaximumTargetCount = { kind = "number", fallback = 0, min = 0, max = 128, integer = true },
        GreenInitialSpeedTilesPerSecond = { kind = "number", fallback = 1.45, min = 0.1, max = 30 },
        GreenLowSpeedDurationSeconds = { kind = "number", fallback = 3, min = 0, max = 10 },
        GreenTargetReacquisitionRadiusTiles = { kind = "number", fallback = 12, min = 1, max = 30 },
        GreenMaximumReacquisitionCount = { kind = "number", fallback = 0, min = 0, max = 64, integer = true },
        GreenWhiteHungerCost = { kind = "number", fallback = 0, min = 0, max = 1 },
        GreenWhiteSafetyFloorPercent = { kind = "number", fallback = 0, min = 0, max = 95, integer = true },
        GreenWhiteCooldownSeconds = { kind = "number", fallback = 0, min = 0, max = 300 },
        RedCraftCooldownSeconds = { kind = "number", fallback = 0, min = 0, max = 3600 },
        RedUseCooldownSeconds = { kind = "number", fallback = 0, min = 0, max = 3600 },
        RedSuccessfulUseConsumesCount = { kind = "number", fallback = 1, min = 1, max = 20, integer = true },
        RedFailedUseConsumesCount = { kind = "number", fallback = 0, min = 0, max = 20, integer = true },
        RedPanicReduction = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        RedBoredomReduction = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        RedUnhappinessReduction = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        MarkerSpacing = { kind = "number", fallback = 4, min = 0, max = 32, integer = true },
        MarkerUpdateIntervalFrames = { kind = "number", fallback = 15, min = 1, max = 120, integer = true },
        SchedulerUpdateIntervalFrames = { kind = "number", fallback = 1, min = 1, max = 120, integer = true },
        WorldQueryIntervalFrames = { kind = "number", fallback = 1, min = 1, max = 120, integer = true },
        NearbyZombieCacheRefreshFrames = { kind = "number", fallback = 12, min = 1, max = 240, integer = true },
        UIRefreshIntervalFrames = { kind = "number", fallback = 15, min = 1, max = 120, integer = true },
        TargetReacquisitionIntervalFrames = { kind = "number", fallback = 15, min = 1, max = 120, integer = true },
        PerformancePreset = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        YellowDistanceCurveMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        YellowMarkerColorThresholds = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        PurpleMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        GreenMeleeMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        GreenTargetPriorityMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        GreenWhiteMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        RedDefaultMode = { kind = "number", fallback = 1, min = 1, max = 2, integer = true },
        RedMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        CompatibilityMode = { kind = "boolean", fallback = true },
        LegacySaveMigration = { kind = "boolean", fallback = true },
        YellowEnabled = { kind = "boolean", fallback = true },
        YellowDistanceGrowthEnabled = { kind = "boolean", fallback = true },
        YellowLowEnduranceInjuryRiskEnabled = { kind = "boolean", fallback = true },
        PurpleClearZombieInfectionEnabled = { kind = "boolean", fallback = true },
        PurpleClearFakeInfectionEnabled = { kind = "boolean", fallback = true },
        PurpleClearZombificationEnabled = { kind = "boolean", fallback = true },
        GreenMeleeEnabled = { kind = "boolean", fallback = true },
        GreenMeleeRightClickToggleAllowed = { kind = "boolean", fallback = true },
        GreenFirearmExcluded = { kind = "boolean", fallback = true },
        GreenVehicleExcluded = { kind = "boolean", fallback = true },
        GreenExplosionExcluded = { kind = "boolean", fallback = true },
        GreenShoveExcluded = { kind = "boolean", fallback = true },
        GreenStompExcluded = { kind = "boolean", fallback = true },
        GreenBareHandsExcluded = { kind = "boolean", fallback = true },
        GreenStructureDamageEnabled = { kind = "boolean", fallback = true },
        GreenDoorDamageEnabled = { kind = "boolean", fallback = true },
        GreenThumpableDamageEnabled = { kind = "boolean", fallback = true },
        GreenActiveDoubleClickEnabled = { kind = "boolean", fallback = true },
        GreenTargetReacquisitionEnabled = { kind = "boolean", fallback = true },
        GreenWallBlockingEnabled = { kind = "boolean", fallback = true },
        RedEnabled = { kind = "boolean", fallback = true },
        RedGrantOnOldSave = { kind = "boolean", fallback = true },
        RedRightClickModeToggleEnabled = { kind = "boolean", fallback = true },
        RedDoubleClickCraftEnabled = { kind = "boolean", fallback = true },
        RedClearZombificationEnabled = { kind = "boolean", fallback = true },
        RedClearFakeInfectionEnabled = { kind = "boolean", fallback = true },
        RedUseSoundEnabled = { kind = "boolean", fallback = true },
        RedCraftSoundEnabled = { kind = "boolean", fallback = true },
        MarkersEnabled = { kind = "boolean", fallback = true },
        YellowMarkerEnabled = { kind = "boolean", fallback = true },
        PurpleMarkerEnabled = { kind = "boolean", fallback = true },
        GreenMarkerEnabled = { kind = "boolean", fallback = true },
        RedMarkerEnabled = { kind = "boolean", fallback = true },
        MarkerPositionPersistenceEnabled = { kind = "boolean", fallback = true },
        TooltipEnabled = { kind = "boolean", fallback = true },
        TransactionLogEnabled = { kind = "boolean", fallback = true },
        PurpleLocalZombiePushEnabled = { kind = "boolean", fallback = false },
        GreenKnockbackEnabled = { kind = "boolean", fallback = false },
        GreenKnockdownEnabled = { kind = "boolean", fallback = false },
        GreenPlayerDamageEnabled = { kind = "boolean", fallback = false },
        GreenNPCDamageEnabled = { kind = "boolean", fallback = true },
        GreenAnimalDamageEnabled = { kind = "boolean", fallback = false },
        GreenActiveStructureDamageEnabled = { kind = "boolean", fallback = false },
        GreenVehicleDamageEnabled = { kind = "boolean", fallback = false },
        GreenFireEnabled = { kind = "boolean", fallback = false },
        RedClearNormalWoundInfectionEnabled = { kind = "boolean", fallback = true },
        RedMultiplayerSharingEnabled = { kind = "boolean", fallback = false },
        LowPerformanceUIMode = { kind = "boolean", fallback = false },
        PerformanceStatisticsEnabled = { kind = "boolean", fallback = false },
    },
    aliases = {
        TuningPreset = "Preset",
        YellowEnableDistanceGrowth = "YellowDistanceGrowthEnabled",
        YellowSpeedGrowthRate = "YellowDistanceGrowthRate",
        YellowMaxSpeedMultiplier = "YellowMaximumSpeedMultiplier",
        YellowDistanceDecayDelay = "YellowDecayDelaySeconds",
        YellowDistanceDecayRate = "YellowDecayRate",
        YellowLowEnduranceInjuryRisk = "YellowLowEnduranceInjuryChance",
        PhoenixTriggerHealthPercent = "PurpleTriggerHealthPercent",
        PhoenixBaseCooldownDays = "PurpleBaseCooldownDays",
        PhoenixMinimumCooldownDays = "PurpleMinimumCooldownDays",
        PhoenixEarlyRechargeMaxDays = "PurpleEarlyRecoveryMaximumDays",
        PhoenixInvulnerabilitySeconds = "PurpleInvulnerabilitySeconds",
        PhoenixRestoreEndurancePercent = "PurpleRecoveryEndurancePercent",
        PhoenixClearZombification = "PurpleClearZombificationEnabled",
    },
    safetyFalse = {
        GreenMissCostsEndurance = true,
        GreenPlayerDamageEnabled = true,
        GreenAnimalDamageEnabled = true,
        GreenActiveStructureDamageEnabled = true,
        GreenVehicleDamageEnabled = true,
        GreenFireEnabled = true,
        GreenExperimentalEntityRendering = true,
        GreenKnockbackEnabled = true,
        GreenKnockdownEnabled = true,
        PurpleLocalZombiePushEnabled = true,
        RedMultiplayerSharingEnabled = true,
    },
    safetyZero = {
        PurpleInvulnerabilitySeconds = true,
        PhoenixInvulnerabilitySeconds = true,
        PhoenixProtectDurationSeconds = true,
    },
    safetyOne = {
        MultiplayerAuthorityMode = true,
        YellowMarkerColorThresholds = true,
        PurpleCooldownReadyState = true,
        PurpleCooldownMode = true,
        PurpleMultiplayerAuthority = true,
        GreenMeleeMultiplayerAuthority = true,
        GreenWhiteActionResultMode = true,
        GreenWhiteMultiplayerAuthority = true,
        RedMultiplayerAuthority = true,
    },
    presetNames = { "VANILLA_PLUS", "BALANCED", "ACTION", "OVERPOWERED", "CUSTOM" },
    presetOverrides = {
        VANILLA_PLUS = {},
        BALANCED = { GlobalSkillCostMultiplier = 0.90, YellowMaximumSpeedMultiplier = 1.50, GreenExplosionBaseDamage = 12.0, RedCraftHealthCost = 0.04 },
        ACTION = { GlobalSkillCostMultiplier = 0.70, YellowMaximumSpeedMultiplier = 1.75, GreenCooldownSeconds = 4.0, GreenExplosionBaseDamage = 16.0, RedStarterItemCount = 4 },
        OVERPOWERED = { GlobalSkillCostMultiplier = 0.35, YellowMaximumSpeedMultiplier = 2.25, GreenCooldownSeconds = 2.0, GreenExplosionBaseDamage = 30.0, RedStarterItemCount = 8, PurpleMinimumCooldownDays = 1, PurpleBaseCooldownDays = 1 },
    },
}

XNP_PZ_DistanceRunner.SandboxSchema = Schema
return Schema
