XNP_PZ_DistanceRunner = XNP_PZ_DistanceRunner or {}

local Schema = {
    namespace = "XNPDistanceRunner",
    specs = {
        EnableMod = { kind = "boolean", fallback = true },
        TuningPreset = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        EnableDebugSummary = { kind = "boolean", fallback = false },
        LiveRefreshTuning = { kind = "boolean", fallback = true },
        GlobalSkillCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        ZombieImpactCostMultiplier = { kind = "number", fallback = 0.24, min = 0.00, max = 2.00 },
        JogBumpCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        SprintPrecollisionCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        SprintVehicleZombieCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        ControlledEscapeCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        NativeTripCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        StaminaAssistIntensity = { kind = "number", fallback = 1.00, min = 0.00, max = 2.00 },
        BlueRefundPercent = { kind = "number", fallback = 30, min = 0, max = 90, integer = true },
        YellowRefundPercent = { kind = "number", fallback = 38, min = 0, max = 90, integer = true },
        RedRefundPercent = { kind = "number", fallback = 55, min = 0, max = 90, integer = true },
        ExtraHungerCostMultiplier = { kind = "number", fallback = 1.00, min = 0.00, max = 3.00 },
        ResourceGateEnabled = { kind = "boolean", fallback = true },
        GreenExitPercent = { kind = "number", fallback = 70, min = 40, max = 95, integer = true },
        GreenEnterPercent = { kind = "number", fallback = 76, min = 45, max = 100, integer = true },
        BlueLowerPercent = { kind = "number", fallback = 36, min = 10, max = 80, integer = true },
        YellowLowerPercent = { kind = "number", fallback = 14, min = 1, max = 60, integer = true },
        ShowStatusIcon = { kind = "boolean", fallback = true },
        EnableStatusShake = { kind = "boolean", fallback = true },
        PerformanceMode = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        IdleThreatScanMs = { kind = "number", fallback = 500, min = 100, max = 2000, integer = true },
        ActiveThreatScanMs = { kind = "number", fallback = 100, min = 50, max = 1000, integer = true },
        CriticalThreatScanMs = { kind = "number", fallback = 50, min = 25, max = 500, integer = true },
        MaxNearbyCandidates = { kind = "number", fallback = 16, min = 4, max = 16, integer = true },
        EnableRuntimeDebug = { kind = "boolean", fallback = false },
        EnableLowEnduranceFoodConversion = { kind = "boolean", fallback = true },
        EnableTieredFoodRecovery = { kind = "boolean", fallback = true },
        FoodRecoveryPulseSeconds = { kind = "number", fallback = 2.00, min = 0.50, max = 10.00 },
        BlueFoodCostPercent = { kind = "number", fallback = 0.50, min = 0.00, max = 10.00 },
        BlueEnduranceGainPercent = { kind = "number", fallback = 1.50, min = 0.01, max = 20.00 },
        YellowRedFoodCostPercent = { kind = "number", fallback = 1.00, min = 0.00, max = 10.00 },
        YellowRedEnduranceGainPercent = { kind = "number", fallback = 2.00, min = 0.01, max = 20.00 },
        FoodConversionTriggerPercent = { kind = "number", fallback = 30, min = 5, max = 95, integer = true },
        FoodConversionTargetPercent = { kind = "number", fallback = 40, min = 5, max = 95, integer = true },
        MinimumFoodReservePercent = { kind = "number", fallback = 40, min = 40, max = 95, integer = true },
        FoodToEnduranceRatioPercent = { kind = "number", fallback = 100, min = 25, max = 400, integer = true },
        FoodConversionRatePercentPerSecond = { kind = "number", fallback = 1, min = 1, max = 10, integer = true },
        EnableHighEnduranceMeleePower = { kind = "boolean", fallback = true },
        MeleePowerStartEndurancePercent = { kind = "number", fallback = 80, min = 1, max = 100, integer = true },
        MeleePowerFullEndurancePercent = { kind = "number", fallback = 95, min = 1, max = 100, integer = true },
        MeleePowerMaxMultiplier = { kind = "number", fallback = 2.00, min = 1.00, max = 2.00 },
        EnablePhoenixTraitLogic = { kind = "boolean", fallback = true },
        PhoenixTraitPointCost = { kind = "number", fallback = 1, min = 1, max = 20, integer = true },
        PhoenixTriggerHealthPercent = { kind = "number", fallback = 20, min = 20, max = 20, integer = true },
        PhoenixBaseCooldownDays = { kind = "number", fallback = 7, min = 1, max = 30, integer = true },
        PhoenixRequirePanicZeroToRecharge = { kind = "boolean", fallback = true },
        PhoenixPanicZeroThreshold = { kind = "number", fallback = 0, min = 0, max = 100, integer = true },
        PhoenixEarlyRechargeEnabled = { kind = "boolean", fallback = true },
        PhoenixEarlyRechargeMaxDays = { kind = "number", fallback = 2, min = 0, max = 6, integer = true },
        PhoenixMinimumCooldownDays = { kind = "number", fallback = 5, min = 1, max = 30, integer = true },
        PhoenixWellFedCreditMaxDays = { kind = "number", fallback = 1, min = 0, max = 6, integer = true },
        PhoenixHealthyCreditMaxDays = { kind = "number", fallback = 1, min = 0, max = 6, integer = true },
        PhoenixWellFedRequiredGameHours = { kind = "number", fallback = 24, min = 1, max = 720, integer = true },
        PhoenixHealthyRequiredGameHours = { kind = "number", fallback = 24, min = 1, max = 720, integer = true },
        PhoenixHealthyMinHealthPercent = { kind = "number", fallback = 95, min = 50, max = 100, integer = true },
        PhoenixProtectRadius = { kind = "number", fallback = 3.00, min = 1.00, max = 3.50 },
        PhoenixRestoreEndurancePercent = { kind = "number", fallback = 100, min = 25, max = 100, integer = true },
        PhoenixFullCureToggle = { kind = "boolean", fallback = true },
        PhoenixClearZombification = { kind = "boolean", fallback = true },
        PhoenixShowStatusIcon = { kind = "boolean", fallback = true },
        PhoenixTooltipEnable = { kind = "boolean", fallback = true },
        PhoenixIconShakeDuringInvulnerability = { kind = "boolean", fallback = true },
        Preset = { kind = "number", fallback = 1, min = 1, max = 5, integer = true },
        EnableYellowTraitSystem = { kind = "boolean", fallback = true },
        EnablePurplePhoenixSystem = { kind = "boolean", fallback = true },
        EnableGreenTraitSystem = { kind = "boolean", fallback = true },
        EnableRedTraitSystem = { kind = "boolean", fallback = true },
        EnableRoundMarkers = { kind = "boolean", fallback = true },
        EnableTooltips = { kind = "boolean", fallback = true },
        EnableSounds = { kind = "boolean", fallback = true },
        HideMarkersWithMap = { kind = "boolean", fallback = true },
        DiagnosticLogLevel = { kind = "number", fallback = 2, min = 1, max = 4, integer = true },
        MultiplayerAuthorityMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        YellowEnableDistanceGrowth = { kind = "boolean", fallback = true },
        YellowSpeedGrowthRate = { kind = "number", fallback = 0.02, min = 0, max = 0.2 },
        YellowMaxSpeedMultiplier = { kind = "number", fallback = 1.4, min = 1, max = 3 },
        YellowDistanceDecayDelay = { kind = "number", fallback = 2, min = 0, max = 30 },
        YellowDistanceDecayRate = { kind = "number", fallback = 0.05, min = 0, max = 1 },
        YellowJogBumpEnabled = { kind = "boolean", fallback = true },
        YellowSprintImpactEnabled = { kind = "boolean", fallback = true },
        YellowSprintTripImmunityEnabled = { kind = "boolean", fallback = true },
        YellowGrabBreakoutEnabled = { kind = "boolean", fallback = true },
        YellowEmergencyGetupEnabled = { kind = "boolean", fallback = true },
        YellowContactEnduranceCost = { kind = "number", fallback = 0.025, min = 0, max = 0.5 },
        YellowGrabEnduranceCost = { kind = "number", fallback = 0.06, min = 0, max = 0.75 },
        YellowLowEnduranceInjuryRisk = { kind = "number", fallback = 0.15, min = 0, max = 1 },
        YellowMarkerShakeEnabled = { kind = "boolean", fallback = true },
        YellowMarkerShakeIntensity = { kind = "number", fallback = 1, min = 0, max = 3 },
        PurpleEnabled = { kind = "boolean", fallback = true },
        PurpleTriggerHealthPercent = { kind = "number", fallback = 20, min = 1, max = 50, integer = true },
        PurpleCooldownMode = { kind = "number", fallback = 1, min = 1, max = 1, integer = true },
        PurpleCooldownRealSeconds = { kind = "number", fallback = 5, min = 1, max = 300 },
        PurpleRecoveryHealthPercent = { kind = "number", fallback = 100, min = 1, max = 100, integer = true },
        PurpleRecoveryEndurancePercent = { kind = "number", fallback = 100, min = 1, max = 100, integer = true },
        PurpleFallProtectionEnabled = { kind = "boolean", fallback = true },
        PurpleRangedPredeathProtectionEnabled = { kind = "boolean", fallback = true },
        PurplePanicGateEnabled = { kind = "boolean", fallback = true },
        PurpleManualToggleEnabled = { kind = "boolean", fallback = true },
        PurpleCooldownReadyState = { kind = "number", fallback = 1, min = 1, max = 5, integer = true },
        PurpleDiagnosticDeathLogEnabled = { kind = "boolean", fallback = false },
        GreenMeleeEnabledByDefault = { kind = "boolean", fallback = true },
        GreenHighTierEndurancePercent = { kind = "number", fallback = 80, min = 1, max = 100, integer = true },
        GreenMidTierEndurancePercent = { kind = "number", fallback = 40, min = 1, max = 100, integer = true },
        GreenHighTierDamageMultiplier = { kind = "number", fallback = 8, min = 1, max = 20 },
        GreenMidTierDamageMultiplier = { kind = "number", fallback = 5, min = 1, max = 20 },
        GreenLowTierDamageMultiplier = { kind = "number", fallback = 2.5, min = 1, max = 20 },
        GreenHighTierEnduranceCost = { kind = "number", fallback = 3, min = 0, max = 25 },
        GreenMidTierEnduranceCost = { kind = "number", fallback = 2, min = 0, max = 25 },
        GreenLowTierEnduranceCost = { kind = "number", fallback = 1, min = 0, max = 25 },
        GreenStructureDamageMultiplier = { kind = "number", fallback = 20, min = 1, max = 50 },
        GreenMissCostsEndurance = { kind = "boolean", fallback = false },
        GreenActiveSkillEnabled = { kind = "boolean", fallback = true },
        GreenActiveMode = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        GreenCooldownRealSeconds = { kind = "number", fallback = 5, min = 0.5, max = 120 },
        GreenTargetSearchRadiusTiles = { kind = "number", fallback = 19.2, min = 1, max = 30 },
        GreenGuidanceInertiaEnabled = { kind = "boolean", fallback = true },
        GreenGuidanceTargetSampleIntervalMs = { kind = "number", fallback = 150, min = 50, max = 500, integer = true },
        GreenGuidanceTurnLevel = { kind = "number", fallback = 4, min = 1, max = 4, integer = true },
        GreenGuidanceTurnDegreesPerSecond = { kind = "number", fallback = 150, min = 15, max = 360 },
        -- Legacy read-only migration input. Runtime guidance uses the explicit degrees-per-second key.
        GreenGuidanceMaxTurnRateDegreesPerSecond = { kind = "number", fallback = 180, min = 30, max = 720 },
        GreenGuidanceRetargetAdaptationMs = { kind = "number", fallback = 350, min = 0, max = 1500, integer = true },
        GreenGuidanceTargetLostBallisticMs = { kind = "number", fallback = 250, min = 0, max = 1000, integer = true },
        GreenGuidanceLeadPredictionSeconds = { kind = "number", fallback = 0.20, min = 0, max = 1 },
        GreenMaximumConcurrentCastsPerPlayer = { kind = "number", fallback = 20, min = 1, max = 20, integer = true },
        GreenMaximumConcurrentCastsGlobal = { kind = "number", fallback = 40, min = 1, max = 80, integer = true },
        GreenCooldownEnabled = { kind = "boolean", fallback = true },
        GreenCastFatigueCostPercent = { kind = "number", fallback = 30, min = 0, max = 100 },
        GreenCastFatigueCostEnabled = { kind = "boolean", fallback = true },
        GreenCastEnduranceCostPercent = { kind = "number", fallback = 5, min = 0, max = 100 },
        GreenCastEnduranceCostEnabled = { kind = "boolean", fallback = true },
        GreenUniqueTargetReservationEnabled = { kind = "boolean", fallback = true },
        GreenLaunchForwardOffsetTiles = { kind = "number", fallback = 0, min = 0, max = 2 },
        GreenSpawnAtExactPlayerPosition = { kind = "boolean", fallback = true },
        GreenRapidCastRandomDirectionEnabled = { kind = "boolean", fallback = true },
        GreenRapidCastWindowMs = { kind = "number", fallback = 1000, min = 100, max = 5000, integer = true },
        GreenRapidCastRandomDirectionMode = { kind = "number", fallback = 1, min = 1, max = 1, integer = true },
        GreenRapidCastSpawnAtExactPlayerPosition = { kind = "boolean", fallback = true },
        GreenContinuousRollingCastEnabled = { kind = "boolean", fallback = true },
        GreenRollingCastRetainedCount = { kind = "number", fallback = 19, min = 1, max = 20, integer = true },
        GreenRollingCastEvictOldestEnabled = { kind = "boolean", fallback = true },
        GreenPreLockCruiseSpeedTilesPerSecond = { kind = "number", fallback = 2.0, min = 0.1, max = 12 },
        GreenTargetScanIntervalMs = { kind = "number", fallback = 150, min = 50, max = 1000, integer = true },
        GreenTargetScanStaggerEnabled = { kind = "boolean", fallback = true },
        GreenDynamicAccelerationEnabled = { kind = "boolean", fallback = true },
        GreenLockedAccelerationTilesPerSecondSquared = { kind = "number", fallback = 1.10, min = 0, max = 10 },
        GreenLockedMaxSpeedTilesPerSecond = { kind = "number", fallback = 12, min = 4, max = 20 },
        GreenLockedConstantSpeedTilesPerSecond = { kind = "number", fallback = 4.5, min = 0.1, max = 30 },
        GreenAccelerationBlendMs = { kind = "number", fallback = 300, min = 1, max = 3000, integer = true },
        GreenAccelerationTimeToMaxSeconds = { kind = "number", fallback = 4.5, min = 0.5, max = 15 },
        GreenAccelerationNoticeableBySeconds = { kind = "number", fallback = 1.5, min = 0.1, max = 5 },
        GreenAccelerationCurveMode = { kind = "number", fallback = 1, min = 1, max = 1, integer = true },
        GreenTargetLostDecelerationEnabled = { kind = "boolean", fallback = true },
        GreenTargetLostDecelerationSeconds = { kind = "number", fallback = 2, min = 0.25, max = 10 },
        GreenTargetLostMinimumSpeedTilesPerSecond = { kind = "number", fallback = 2.0, min = 0.1, max = 12 },
        GreenTargetFlashEnabled = { kind = "boolean", fallback = false },
        GreenTargetFlashIntervalMs = { kind = "number", fallback = 500, min = 100, max = 5000, integer = true },
        GreenTargetFlashDurationMs = { kind = "number", fallback = 120, min = 30, max = 1000, integer = true },
        GreenTargetFlashStaggerEnabled = { kind = "boolean", fallback = true },
        GreenTargetFeedbackMode = { kind = "number", fallback = 0, min = 0, max = 2, integer = true },
        GreenOrbVisualStyle = { kind = "number", fallback = 6, min = 1, max = 6, integer = true },
        GreenOrbSpinEnabled = { kind = "boolean", fallback = true },
        GreenOrbSpinDegreesPerSecond = { kind = "number", fallback = 180, min = 0, max = 1080 },
        GreenOrbSpinFrameCount = { kind = "number", fallback = 16, min = 1, max = 16, integer = true },
        GreenOrbGlowPulseEnabled = { kind = "boolean", fallback = false },
        GreenOrbGlowPulseHz = { kind = "number", fallback = 1.25, min = 0.1, max = 12 },
        GreenOrbGlowJitterEnabled = { kind = "boolean", fallback = false },
        GreenOrbGlowJitterPixels = { kind = "number", fallback = 0, min = 0, max = 6 },
        GreenOrbGlowOrbitPixels = { kind = "number", fallback = 0, min = 0, max = 6 },
        GreenOrbGlowMinAlpha = { kind = "number", fallback = 0.42, min = 0, max = 1 },
        GreenOrbGlowMaxAlpha = { kind = "number", fallback = 0.75, min = 0, max = 1 },
        GreenBloomCoreDiameterPx = { kind = "number", fallback = 32, min = 20, max = 42, integer = true },
        GreenBloomRingDiameterPx = { kind = "number", fallback = 48, min = 28, max = 96, integer = true },
        GreenBloomGlowDiameterPx = { kind = "number", fallback = 72, min = 40, max = 144, integer = true },
        GreenBloomScalePercent = { kind = "number", fallback = 100, min = 50, max = 200, integer = true },
        GreenBloomPulseHz = { kind = "number", fallback = 0.85, min = 0.20, max = 2.0 },
        GreenBloomGlowMinAlpha = { kind = "number", fallback = 0.22, min = 0.10, max = 0.60 },
        GreenBloomGlowMaxAlpha = { kind = "number", fallback = 0.42, min = 0.10, max = 0.75 },
        GreenBloomTrailEnabled = { kind = "boolean", fallback = true },
        GreenBloomTrailSegments = { kind = "number", fallback = 2, min = 0, max = 3, integer = true },
        GreenBloomReducedFlashing = { kind = "boolean", fallback = true },
        XNPVisualQualityPreset = { kind = "number", fallback = 2, min = 1, max = 4, integer = true },
        GreenLethalRadiusTiles = { kind = "number", fallback = 3.5, min = 0.1, max = 15 },
        GreenKnockdownRadiusTiles = { kind = "number", fallback = 7, min = 0.1, max = 20 },
        GreenOuterKnockdownEnabled = { kind = "boolean", fallback = true },
        GreenImpactDamageDelayMs = { kind = "number", fallback = 0, min = 0, max = 1000, integer = true },
        GreenImpactVisualLifetimeMs = { kind = "number", fallback = 140, min = 40, max = 1000, integer = true },
        GreenImpactVisualScale = { kind = "number", fallback = 1, min = 0.25, max = 4 },
        GreenProjectileArmRenderFrames = { kind = "number", fallback = 1, min = 1, max = 30, integer = true },
        GreenImpactSoundVolumePercent = { kind = "number", fallback = 100, min = 0, max = 100, integer = true },
        GreenTargetQueryCacheMs = { kind = "number", fallback = 100, min = 50, max = 500, integer = true },
        GreenMaximumTargetScansPerFrame = { kind = "number", fallback = 2, min = 1, max = 8, integer = true },
        GreenPerformanceStatisticsEnabled = { kind = "boolean", fallback = false },
        GreenNoTargetSearchSeconds = { kind = "number", fallback = 3.0, min = 0.1, max = 10 },
        GreenImpactVisualHoldMs = { kind = "number", fallback = 300, min = 100, max = 1000, integer = true },
        GreenInitialSpeedMultiplier = { kind = "number", fallback = 1, min = 0.1, max = 5 },
        GreenAccelerationStartSeconds = { kind = "number", fallback = 3, min = 0, max = 10 },
        GreenAccelerationMultiplierPerSecond = { kind = "number", fallback = 1.5, min = 1, max = 3 },
        GreenMaximumVirtualSpeedTilesPerSecond = { kind = "number", fallback = 12, min = 0.5, max = 30 },
        GreenMaximumFlightSeconds = { kind = "number", fallback = 15, min = 0.5, max = 30 },
        GreenImpactDistanceTiles = { kind = "number", fallback = 0.55, min = 0.1, max = 2 },
        GreenAnyValidCollisionDetonationEnabled = { kind = "boolean", fallback = true },
        GreenCollisionCharactersEnabled = { kind = "boolean", fallback = true },
        GreenCollisionWorldSolidsEnabled = { kind = "boolean", fallback = true },
        GreenCollisionVehiclesEnabled = { kind = "boolean", fallback = true },
        GreenCollisionArmingDelayMs = { kind = "number", fallback = 250, min = 0, max = 1000, integer = true },
        GreenCollisionArmingMinimumTravelTiles = { kind = "number", fallback = 0.75, min = 0, max = 2 },
        GreenSpawnSafetyRadiusTiles = { kind = "number", fallback = 0.85, min = 0.10, max = 2.00 },
        GreenCollisionRadiusTiles = { kind = "number", fallback = 0.45, min = 0.1, max = 1.5 },
        GreenCollisionSweptTestEnabled = { kind = "boolean", fallback = true },
        GreenExplosionRadiusTiles = { kind = "number", fallback = 7, min = 0.5, max = 15 },
        GreenExplosionBaseDamage = { kind = "number", fallback = 10, min = 0.1, max = 100 },
        GreenExplosionFalloffEnabled = { kind = "boolean", fallback = true },
        GreenTargetOutlineEnabled = { kind = "boolean", fallback = false },
        GreenLockAreaEnabled = { kind = "boolean", fallback = true },
        GreenLockAreaRadiusTiles = { kind = "number", fallback = 8, min = 1, max = 12 },
        GreenLockOutlinePulseEnabled = { kind = "boolean", fallback = true },
        GreenLockOutlinePulseIntervalSeconds = { kind = "number", fallback = 3, min = 0.5, max = 30 },
        GreenLockOutlinePulseDurationSeconds = { kind = "number", fallback = 0.65, min = 0.1, max = 5 },
        GreenBanditDamageEnabled = { kind = "boolean", fallback = true },
        GreenRuntimeTestModeEnabled = { kind = "boolean", fallback = false },
        GreenRuntimeTestNoCooldown = { kind = "boolean", fallback = false },
        GreenRuntimeTestIgnoreResourceAdmission = { kind = "boolean", fallback = false },
        GreenRuntimeTestStillApplyCosts = { kind = "boolean", fallback = true },
        GreenRuntimeTestAllowCastAtMaxFatigue = { kind = "boolean", fallback = false },
        GreenRuntimeTestAllowCastAtZeroEndurance = { kind = "boolean", fallback = false },
        GreenVisualMaximumFPS = { kind = "number", fallback = 60, min = 15, max = 60, integer = true },
        GreenSimulationUpdatesPerSecond = { kind = "number", fallback = 30, min = 20, max = 60, integer = true },
        GreenDynamicLightEnabled = { kind = "boolean", fallback = true },
        GreenDynamicLightFlightEnabled = { kind = "boolean", fallback = true },
        GreenDynamicLightFollowEnabled = { kind = "boolean", fallback = true },
        GreenDynamicLightImpactEnabled = { kind = "boolean", fallback = true },
        GreenDynamicLightRadiusTiles = { kind = "number", fallback = 3, min = 1, max = 12 },
        GreenDynamicLightIntensityPercent = { kind = "number", fallback = 70, min = 1, max = 100, integer = true },
        GreenDynamicLightUpdateIntervalMs = { kind = "number", fallback = 150, min = 50, max = 1000, integer = true },
        GreenMaximumActiveDynamicLights = { kind = "number", fallback = 6, min = 1, max = 20, integer = true },
        GreenDynamicLightRed = { kind = "number", fallback = 0.08, min = 0, max = 1 },
        GreenDynamicLightGreen = { kind = "number", fallback = 1.00, min = 0, max = 1 },
        GreenDynamicLightBlue = { kind = "number", fallback = 0.18, min = 0, max = 1 },
        GreenImpactDynamicLightRadiusTiles = { kind = "number", fallback = 5, min = 1, max = 15 },
        GreenImpactDynamicLightIntensityPercent = { kind = "number", fallback = 100, min = 1, max = 100, integer = true },
        GreenImpactDynamicLightLifetimeMs = { kind = "number", fallback = 220, min = 50, max = 2000, integer = true },
        GreenCenterFireEnabled = { kind = "boolean", fallback = true },
        GreenCenterFireSingleSquareOnly = { kind = "boolean", fallback = true },
        GreenCenterFireAllowManualPropagation = { kind = "boolean", fallback = false },
        GreenCenterFireStrength = { kind = "number", fallback = 5, min = 5, max = 100, integer = true },
        GreenCenterFireLifetimeSeconds = { kind = "number", fallback = 8.33, min = 1, max = 60 },
        GreenCenterStructureBreakEnabled = { kind = "boolean", fallback = true },
        GreenCenterStructureBreakRadiusTiles = { kind = "number", fallback = 1.5, min = 0.5, max = 3 },
        GreenCenterBreakWindowsEnabled = { kind = "boolean", fallback = true },
        GreenCenterBreakGlassDoorsEnabled = { kind = "boolean", fallback = true },
        GreenCenterBreakDoorsEnabled = { kind = "boolean", fallback = true },
        GreenCenterBreakWallsEnabled = { kind = "boolean", fallback = false },
        GreenCenterBreakFurnitureEnabled = { kind = "boolean", fallback = false },
        GreenOrbScreenDiameterPx = { kind = "number", fallback = 36, min = 12, max = 128, integer = true },
        GreenOrbGlowDiameterPx = { kind = "number", fallback = 48, min = 16, max = 160, integer = true },
        GreenMinimumVisibleFlightMs = { kind = "number", fallback = 500, min = 100, max = 5000, integer = true },
        GreenMinimumInflightRenderFrames = { kind = "number", fallback = 1, min = 1, max = 30, integer = true },
        GreenInflightDiagnosticBorderEnabled = { kind = "boolean", fallback = false },
        GreenCastSoundEnabled = { kind = "boolean", fallback = true },
        GreenImpactSoundEnabled = { kind = "boolean", fallback = true },
        GreenRefundCooldownOnNoTarget = { kind = "boolean", fallback = true },
        GreenExperimentalEntityRendering = { kind = "boolean", fallback = false },
        GreenWhiteActionEnabled = { kind = "boolean", fallback = true },
        GreenWhiteActionDurationSeconds = { kind = "number", fallback = 4, min = 0.5, max = 30 },
        GreenWhiteHealthCost = { kind = "number", fallback = 0.05, min = 0, max = 0.5 },
        GreenWhiteEnduranceCost = { kind = "number", fallback = 0.15, min = 0, max = 1 },
        GreenWhiteUnhappinessCost = { kind = "number", fallback = 5, min = 0, max = 100 },
        GreenWhiteBoredomCost = { kind = "number", fallback = 5, min = 0, max = 100 },
        GreenWhiteMidActionSoundEnabled = { kind = "boolean", fallback = true },
        GreenWhiteActionResultMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        RedStarterItemCount = { kind = "number", fallback = 3, min = 0, max = 20, integer = true },
        RedCraftEnabled = { kind = "boolean", fallback = true },
        RedCraftDurationSeconds = { kind = "number", fallback = 4, min = 0.5, max = 60 },
        RedCraftHealthCost = { kind = "number", fallback = 0.05, min = 0, max = 0.5 },
        RedCraftHealthCostPoints = { kind = "number", fallback = 10, min = 0, max = 99 },
        RedCraftUnhappinessReductionPoints = { kind = "number", fallback = 10, min = 0, max = 100, integer = true },
        RedCraftUnhappinessCost = { kind = "number", fallback = 10, min = 0, max = 100, integer = true },
        RedPCraftBoredomReduction = { kind = "number", fallback = 30, min = 0, max = 100, integer = true },
        RedCraftHungerCost = { kind = "number", fallback = 0.1, min = 0, max = 1 },
        RedCraftSweatEnabled = { kind = "boolean", fallback = true },
        RedCraftSweatIntensity = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        RedCraftFatigueCostPercent = { kind = "number", fallback = 10, min = 0, max = 100 },
        RedCraftBodyHeatEnabled = { kind = "boolean", fallback = true },
        RedCraftExertionFeedbackEnabled = { kind = "boolean", fallback = true },
        RedCraftPhysicalLoadDurationSeconds = { kind = "number", fallback = 20, min = 1, max = 120 },
        RedCraftPhysicalLoadStackLimit = { kind = "number", fallback = 3, min = 1, max = 3, integer = true },
        RedCraftHeatFeedbackIntensity = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        RedCraftExertionFeedbackIntensity = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        RedCraftMinimumVisibleFeedbackMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        RedCraftImmediateFullSweatEnabled = { kind = "boolean", fallback = true },
        RedCraftImmediateSweatPercent = { kind = "number", fallback = 100, min = 0, max = 100, integer = true },
        RedCraftImmediateTemperatureIncreaseC = { kind = "number", fallback = 0.5, min = 0, max = 1.5 },
        RedCraftMaximumBodyTemperatureC = { kind = "number", fallback = 38.5, min = 37, max = 40 },
        RedCraftImmediateEnduranceTargetPercent = { kind = "number", fallback = 10, min = 5, max = 50, integer = true },
        RedPhysicalLoadRingEnabled = { kind = "boolean", fallback = false },
        RedSafetyFloorPercent = { kind = "number", fallback = 20, min = 1, max = 95, integer = true },
        RedStaminaImmediateRecovery = { kind = "number", fallback = 0.5, min = 0, max = 1 },
        RedStaminaPeriodicRecovery = { kind = "number", fallback = 0.05, min = 0, max = 1 },
        RedStaminaPeriodicIntervalSeconds = { kind = "number", fallback = 2, min = 0.5, max = 60 },
        RedStaminaPeriodicDurationSeconds = { kind = "number", fallback = 20, min = 0, max = 300 },
        RedFatigueReduction = { kind = "number", fallback = 0.25, min = 0, max = 1 },
        RedMoodReductionPercent = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        RedHealingHealthAmount = { kind = "number", fallback = 25, min = 0, max = 100 },
        RedHealFractureEnabled = { kind = "boolean", fallback = true },
        RedClearZombieInfectionEnabled = { kind = "boolean", fallback = true },
        RedHealMinorWoundCount = { kind = "number", fallback = 3, min = 0, max = 20, integer = true },
        RedHealMajorWoundCount = { kind = "number", fallback = 1, min = 0, max = 20, integer = true },
        MarkerScale = { kind = "number", fallback = 1, min = 0.5, max = 2 },
        MarkerOpacity = { kind = "number", fallback = 1, min = 0.2, max = 1 },
        MarkerDragEnabled = { kind = "boolean", fallback = true },
        MarkerResetPositions = { kind = "boolean", fallback = false },
        TooltipDetailLevel = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        EnableTargetOutline = { kind = "boolean", fallback = true },
        PerformanceUpdateIntervalFrames = { kind = "number", fallback = 6, min = 1, max = 120, integer = true },
        EvidenceLogEnabled = { kind = "boolean", fallback = false },
        YellowDistanceGrowthRate = { kind = "number", fallback = 0.02, min = 0, max = 0.2 },
        YellowInitialSpeedMultiplier = { kind = "number", fallback = 1, min = 1, max = 3 },
        YellowMaximumSpeedMultiplier = { kind = "number", fallback = 1.4, min = 1, max = 3 },
        YellowDecayDelaySeconds = { kind = "number", fallback = 2, min = 0, max = 30 },
        YellowDecayRate = { kind = "number", fallback = 0.05, min = 0, max = 1 },
        YellowJogMinimumSpeed = { kind = "number", fallback = 1.45, min = 0.1, max = 5 },
        YellowJogImpactForce = { kind = "number", fallback = 1, min = 0, max = 3 },
        YellowJogStaggerChance = { kind = "number", fallback = 0.70, min = 0, max = 1 },
        YellowJogKnockdownChance = { kind = "number", fallback = 0.22, min = 0, max = 1 },
        YellowSprintMinimumSpeed = { kind = "number", fallback = 3.25, min = 0.1, max = 8 },
        YellowSprintImpactForce = { kind = "number", fallback = 1, min = 0, max = 3 },
        YellowSprintStaggerChance = { kind = "number", fallback = 1, min = 0, max = 1 },
        YellowSprintKnockdownChance = { kind = "number", fallback = 1, min = 0, max = 1 },
        YellowGrabBreakoutCooldownSeconds = { kind = "number", fallback = 3, min = 0.1, max = 30 },
        YellowEmergencyGetupCooldownSeconds = { kind = "number", fallback = 0.75, min = 0.1, max = 30 },
        YellowLowEnduranceInjuryChance = { kind = "number", fallback = 0.15, min = 0, max = 1 },
        YellowAltCrowdBreakoutEnabled = { kind = "boolean", fallback = false },
        YellowAltCrowdBreakoutRadiusTiles = { kind = "number", fallback = 1.75, min = 0.5, max = 4 },
        YellowAltCrowdBreakoutMinimumNearbyZombies = { kind = "number", fallback = 3, min = 1, max = 12, integer = true },
        YellowAltCrowdBreakoutCooldownSeconds = { kind = "number", fallback = 8, min = 0.5, max = 60 },
        YellowAltCrowdBreakoutEnduranceCost = { kind = "number", fallback = 0.12, min = 0, max = 1 },
        YellowAltCrowdBreakoutStrongControlOverride = { kind = "boolean", fallback = false },
        YellowAltCrowdBreakoutLowEnduranceMultiplier = { kind = "number", fallback = 0.60, min = 0.10, max = 1 },
        YellowAltCrowdBreakoutNotification = { kind = "boolean", fallback = false },
        YellowMomentumRingEnabled = { kind = "boolean", fallback = false },
        YellowContactImpactVFXEnabled = { kind = "boolean", fallback = false },
        YellowAltCrowdBreakoutTestPresetEnabled = { kind = "boolean", fallback = false },
        PurpleBaseCooldownDays = { kind = "number", fallback = 7, min = 1, max = 30, integer = true },
        PurpleMinimumCooldownDays = { kind = "number", fallback = 5, min = 1, max = 30, integer = true },
        PurpleEarlyRecoveryMaximumDays = { kind = "number", fallback = 2, min = 0, max = 6, integer = true },
        PurpleInvulnerabilitySeconds = { kind = "number", fallback = 10, min = 0, max = 30 },
        PurplePhoenixWorldBloomEnabled = { kind = "boolean", fallback = false },
        PurplePhoenixInvulnerabilityRingEnabled = { kind = "boolean", fallback = false },
        PurpleLifeStockTooltipSummaryEnabled = { kind = "boolean", fallback = false },
        PurpleMaximumTriggerCount = { kind = "number", fallback = 0, min = 0, max = 999, integer = true },
        GreenDisabledDamageMultiplier = { kind = "number", fallback = 1, min = 1, max = 20 },
        GreenCooldownSeconds = { kind = "number", fallback = 5, min = 0.5, max = 120 },
        GreenMaximumTargetCount = { kind = "number", fallback = 0, min = 0, max = 128, integer = true },
        GreenInitialSpeedTilesPerSecond = { kind = "number", fallback = 1.45, min = 0.1, max = 30 },
        GreenLowSpeedDurationSeconds = { kind = "number", fallback = 3, min = 0, max = 10 },
        GreenTargetReacquisitionRadiusTiles = { kind = "number", fallback = 19.2, min = 1, max = 30 },
        GreenMaximumReacquisitionCount = { kind = "number", fallback = 0, min = 0, max = 64, integer = true },
        GreenWhiteHungerCost = { kind = "number", fallback = 0, min = 0, max = 1 },
        GreenWhiteSafetyFloorPercent = { kind = "number", fallback = 0, min = 0, max = 95, integer = true },
        GreenWhiteCooldownSeconds = { kind = "number", fallback = 0, min = 0, max = 300 },
        RedCraftCooldownSeconds = { kind = "number", fallback = 0, min = 0, max = 3600 },
        RedUseCooldownSeconds = { kind = "number", fallback = 0, min = 0, max = 3600 },
        RedSuccessfulUseConsumesCount = { kind = "number", fallback = 1, min = 1, max = 20, integer = true },
        RedFailedUseConsumesCount = { kind = "number", fallback = 0, min = 0, max = 20, integer = true },
        RedPanicReduction = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        RedBoredomReduction = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        RedUnhappinessReduction = { kind = "number", fallback = 50, min = 0, max = 100, integer = true },
        MarkerSpacing = { kind = "number", fallback = 4, min = 0, max = 32, integer = true },
        MarkerUpdateIntervalFrames = { kind = "number", fallback = 15, min = 1, max = 120, integer = true },
        SchedulerUpdateIntervalFrames = { kind = "number", fallback = 1, min = 1, max = 120, integer = true },
        WorldQueryIntervalFrames = { kind = "number", fallback = 1, min = 1, max = 120, integer = true },
        NearbyZombieCacheRefreshFrames = { kind = "number", fallback = 12, min = 1, max = 240, integer = true },
        UIRefreshIntervalFrames = { kind = "number", fallback = 15, min = 1, max = 120, integer = true },
        TargetReacquisitionIntervalFrames = { kind = "number", fallback = 15, min = 1, max = 120, integer = true },
        PerformancePreset = { kind = "number", fallback = 2, min = 1, max = 3, integer = true },
        YellowDistanceCurveMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        YellowMarkerColorThresholds = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        PurpleMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        GreenMeleeMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        GreenTargetPriorityMode = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        GreenWhiteMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        RedDefaultMode = { kind = "number", fallback = 1, min = 1, max = 2, integer = true },
        RedMultiplayerAuthority = { kind = "number", fallback = 1, min = 1, max = 3, integer = true },
        CompatibilityMode = { kind = "boolean", fallback = true },
        DeveloperTestToolsEnabled = { kind = "boolean", fallback = false },
        GeneralGameplayPreset = { kind = "number", fallback = 1, min = 1, max = 2, integer = true },
        LegacySaveMigration = { kind = "boolean", fallback = true },
        YellowEnabled = { kind = "boolean", fallback = true },
        YellowDistanceGrowthEnabled = { kind = "boolean", fallback = true },
        YellowLowEnduranceInjuryRiskEnabled = { kind = "boolean", fallback = true },
        PurpleClearZombieInfectionEnabled = { kind = "boolean", fallback = true },
        PurpleClearFakeInfectionEnabled = { kind = "boolean", fallback = true },
        PurpleClearZombificationEnabled = { kind = "boolean", fallback = true },
        PurpleRightClickRepairEnabled = { kind = "boolean", fallback = true },
        PurpleBackupBoredomIncreasePoints = {
            kind = "number", fallback = 50, min = 0, max = 100, integer = true,
        },
        PurpleBackupUnhappinessDecreasePoints = {
            kind = "number", fallback = 50, min = 0, max = 100, integer = true,
        },
        PurpleBackupEnduranceCostPoints = {
            kind = "number", fallback = 80, min = 0, max = 100, integer = true,
        },
        PurpleBackupHungerIncreasePoints = {
            kind = "number", fallback = 10, min = 0, max = 100, integer = true,
        },
        PurpleBackupManualRecordEnabled = { kind = "boolean", fallback = true },
        PurpleBackupAutoRecordEnabled = { kind = "boolean", fallback = true },
        PurpleAutoRearmAfterSuccessfulRestore = {
            kind = "boolean", fallback = false,
        },
        PurpleBackupAutoRecordIntervalGameDays = {
            kind = "number", fallback = 7, min = 1, max = 365, integer = true,
        },
        PurpleBackupMaximumInventoryCopies = {
            kind = "number", fallback = 1, min = 1, max = 8, integer = true,
        },
        PurpleBackupUseRedSound = { kind = "boolean", fallback = true },
        PurpleBackupCraftDurationSeconds = {
            kind = "number", fallback = 4, min = 1, max = 60, integer = true,
        },
        PurpleBackupRestoreDurationSeconds = {
            kind = "number", fallback = 4, min = 1, max = 60, integer = true,
        },
        GreenMeleeEnabled = { kind = "boolean", fallback = true },
        GreenMeleeRightClickToggleAllowed = { kind = "boolean", fallback = true },
        GreenFirearmExcluded = { kind = "boolean", fallback = true },
        GreenVehicleExcluded = { kind = "boolean", fallback = true },
        GreenExplosionExcluded = { kind = "boolean", fallback = true },
        GreenShoveExcluded = { kind = "boolean", fallback = true },
        GreenStompExcluded = { kind = "boolean", fallback = true },
        GreenBareHandsExcluded = { kind = "boolean", fallback = true },
        GreenStructureDamageEnabled = { kind = "boolean", fallback = true },
        GreenDoorDamageEnabled = { kind = "boolean", fallback = true },
        GreenThumpableDamageEnabled = { kind = "boolean", fallback = true },
        GreenActiveDoubleClickEnabled = { kind = "boolean", fallback = true },
        GreenTargetReacquisitionEnabled = { kind = "boolean", fallback = true },
        GreenWallBlockingEnabled = { kind = "boolean", fallback = true },
        RedEnabled = { kind = "boolean", fallback = true },
        RedGrantOnOldSave = { kind = "boolean", fallback = true },
        RedRightClickModeToggleEnabled = { kind = "boolean", fallback = true },
        RedDoubleClickCraftEnabled = { kind = "boolean", fallback = true },
        RedClearZombificationEnabled = { kind = "boolean", fallback = true },
        RedClearFakeInfectionEnabled = { kind = "boolean", fallback = true },
        RedUseSoundEnabled = { kind = "boolean", fallback = true },
        RedCraftSoundEnabled = { kind = "boolean", fallback = true },
        MarkersEnabled = { kind = "boolean", fallback = true },
        YellowMarkerEnabled = { kind = "boolean", fallback = true },
        PurpleMarkerEnabled = { kind = "boolean", fallback = true },
        GreenMarkerEnabled = { kind = "boolean", fallback = true },
        RedMarkerEnabled = { kind = "boolean", fallback = true },
        MarkerPositionPersistenceEnabled = { kind = "boolean", fallback = true },
        TooltipEnabled = { kind = "boolean", fallback = true },
        TransactionLogEnabled = { kind = "boolean", fallback = true },
        PurpleLocalZombiePushEnabled = { kind = "boolean", fallback = true },
        GreenKnockbackEnabled = { kind = "boolean", fallback = false },
        GreenKnockdownEnabled = { kind = "boolean", fallback = false },
        GreenPlayerDamageEnabled = { kind = "boolean", fallback = false },
        GreenNPCDamageEnabled = { kind = "boolean", fallback = true },
        GreenAnimalDamageEnabled = { kind = "boolean", fallback = false },
        GreenActiveStructureDamageEnabled = { kind = "boolean", fallback = false },
        GreenVehicleDamageEnabled = { kind = "boolean", fallback = false },
        GreenFireEnabled = { kind = "boolean", fallback = false },
        RedClearNormalWoundInfectionEnabled = { kind = "boolean", fallback = true },
        RedMultiplayerSharingEnabled = { kind = "boolean", fallback = false },
        LowPerformanceUIMode = { kind = "boolean", fallback = false },
        PerformanceStatisticsEnabled = { kind = "boolean", fallback = false },
    },
    aliases = {
        TuningPreset = "Preset",
        YellowEnableDistanceGrowth = "YellowDistanceGrowthEnabled",
        YellowSpeedGrowthRate = "YellowDistanceGrowthRate",
        YellowMaxSpeedMultiplier = "YellowMaximumSpeedMultiplier",
        YellowDistanceDecayDelay = "YellowDecayDelaySeconds",
        YellowDistanceDecayRate = "YellowDecayRate",
        YellowLowEnduranceInjuryRisk = "YellowLowEnduranceInjuryChance",
        PhoenixTriggerHealthPercent = "PurpleTriggerHealthPercent",
        PhoenixBaseCooldownDays = "PurpleBaseCooldownDays",
        PhoenixMinimumCooldownDays = "PurpleMinimumCooldownDays",
        PhoenixEarlyRechargeMaxDays = "PurpleEarlyRecoveryMaximumDays",
        PhoenixInvulnerabilitySeconds = "PurpleInvulnerabilitySeconds",
        PhoenixProtectDurationSeconds = "PurpleInvulnerabilitySeconds",
        PhoenixRestoreEndurancePercent = "PurpleRecoveryEndurancePercent",
        PhoenixClearZombification = "PurpleClearZombificationEnabled",
    },
    safetyFalse = {
        GreenMissCostsEndurance = true,
        GreenPlayerDamageEnabled = true,
        GreenAnimalDamageEnabled = true,
        GreenActiveStructureDamageEnabled = true,
        GreenVehicleDamageEnabled = true,
        GreenFireEnabled = true,
        GreenExperimentalEntityRendering = true,
        GreenKnockbackEnabled = true,
        GreenKnockdownEnabled = true,
        GreenCenterFireAllowManualPropagation = true,
        GreenCenterBreakWallsEnabled = true,
        GreenCenterBreakFurnitureEnabled = true,
        RedMultiplayerSharingEnabled = true,
    },
    safetyZero = {},
    safetyOne = {
        MultiplayerAuthorityMode = true,
        YellowMarkerColorThresholds = true,
        PurpleCooldownReadyState = true,
        PurpleCooldownMode = true,
        PurpleMultiplayerAuthority = true,
        GreenMeleeMultiplayerAuthority = true,
        GreenWhiteActionResultMode = true,
        GreenWhiteMultiplayerAuthority = true,
        RedMultiplayerAuthority = true,
    },
    presetNames = { "VANILLA_PLUS", "BALANCED", "ACTION", "OVERPOWERED", "CUSTOM" },
    presetOverrides = {
        VANILLA_PLUS = {
            GreenMaximumConcurrentCastsPerPlayer = 20, GreenMaximumConcurrentCastsGlobal = 40,
            GreenLethalRadiusTiles = 3.5, GreenKnockdownRadiusTiles = 7.0,
            GreenRuntimeTestModeEnabled = false, GreenRuntimeTestNoCooldown = false,
            GreenRuntimeTestIgnoreResourceAdmission = false, GreenRuntimeTestStillApplyCosts = true,
            GreenRuntimeTestAllowCastAtMaxFatigue = false,
            GreenRuntimeTestAllowCastAtZeroEndurance = false,
            GreenRapidCastRandomDirectionEnabled = true, GreenRapidCastWindowMs = 1000,
            GreenGuidanceTurnLevel = 4, GreenGuidanceTurnDegreesPerSecond = 150,
            GreenPreLockCruiseSpeedTilesPerSecond = 2.0,
            GreenTargetLostMinimumSpeedTilesPerSecond = 2.0,
            GreenLockedMaxSpeedTilesPerSecond = 12.0, GreenAccelerationTimeToMaxSeconds = 4.5,
            GreenAnyValidCollisionDetonationEnabled = true,
            GreenCollisionCharactersEnabled = true, GreenCollisionWorldSolidsEnabled = true,
            GreenCollisionVehiclesEnabled = true,
        },
        BALANCED = {
            GlobalSkillCostMultiplier = 0.90, YellowMaximumSpeedMultiplier = 1.50,
            GreenExplosionBaseDamage = 12.0, GreenCastFatigueCostPercent = 25,
            GreenMaximumConcurrentCastsPerPlayer = 20, GreenMaximumConcurrentCastsGlobal = 40,
            GreenLethalRadiusTiles = 3.5, GreenKnockdownRadiusTiles = 7.0,
            GreenRuntimeTestModeEnabled = false, GreenRuntimeTestNoCooldown = false,
            GreenRuntimeTestIgnoreResourceAdmission = false, GreenRuntimeTestStillApplyCosts = true,
            GreenRuntimeTestAllowCastAtMaxFatigue = false,
            GreenRuntimeTestAllowCastAtZeroEndurance = false,
            GreenRapidCastRandomDirectionEnabled = true, GreenRapidCastWindowMs = 1000,
            GreenGuidanceTurnLevel = 4, GreenGuidanceTurnDegreesPerSecond = 150,
            GreenPreLockCruiseSpeedTilesPerSecond = 2.0,
            GreenTargetLostMinimumSpeedTilesPerSecond = 2.0,
            GreenLockedMaxSpeedTilesPerSecond = 12.0, GreenAccelerationTimeToMaxSeconds = 4.5,
            GreenAnyValidCollisionDetonationEnabled = true,
            GreenCollisionCharactersEnabled = true, GreenCollisionWorldSolidsEnabled = true,
            GreenCollisionVehiclesEnabled = true,
            RedCraftHealthCostPoints = 8, RedCraftUnhappinessReductionPoints = 10,
        },
        ACTION = {
            GlobalSkillCostMultiplier = 0.70, YellowMaximumSpeedMultiplier = 1.75,
            GreenCooldownSeconds = 4.0, GreenExplosionBaseDamage = 16.0,
            GreenGuidanceTurnLevel = 4, GreenGuidanceTurnDegreesPerSecond = 150,
            GreenGuidanceRetargetAdaptationMs = 250,
            GreenMaximumConcurrentCastsPerPlayer = 20, GreenMaximumConcurrentCastsGlobal = 40,
            GreenCastFatigueCostPercent = 20, GreenLethalRadiusTiles = 3.5,
            GreenRuntimeTestModeEnabled = false, GreenRuntimeTestNoCooldown = false,
            GreenRuntimeTestIgnoreResourceAdmission = false, GreenRuntimeTestStillApplyCosts = true,
            GreenRuntimeTestAllowCastAtMaxFatigue = false,
            GreenRuntimeTestAllowCastAtZeroEndurance = false,
            GreenRapidCastRandomDirectionEnabled = true, GreenRapidCastWindowMs = 1000,
            GreenPreLockCruiseSpeedTilesPerSecond = 2.0,
            GreenTargetLostMinimumSpeedTilesPerSecond = 2.0,
            GreenLockedMaxSpeedTilesPerSecond = 12.0, GreenAccelerationTimeToMaxSeconds = 4.5,
            GreenAnyValidCollisionDetonationEnabled = true,
            GreenCollisionCharactersEnabled = true, GreenCollisionWorldSolidsEnabled = true,
            GreenCollisionVehiclesEnabled = true,
            GreenKnockdownRadiusTiles = 7.0, RedCraftHealthCostPoints = 6,
            RedCraftUnhappinessReductionPoints = 10, RedStarterItemCount = 4,
        },
        OVERPOWERED = {
            GlobalSkillCostMultiplier = 0.35, YellowMaximumSpeedMultiplier = 2.25,
            GreenCooldownSeconds = 2.0, GreenExplosionBaseDamage = 30.0,
            GreenGuidanceTurnLevel = 4, GreenGuidanceTurnDegreesPerSecond = 150,
            GreenGuidanceRetargetAdaptationMs = 150,
            GreenMaximumConcurrentCastsPerPlayer = 20, GreenMaximumConcurrentCastsGlobal = 40,
            GreenCastFatigueCostPercent = 10, GreenLethalRadiusTiles = 3.5,
            GreenRuntimeTestModeEnabled = false, GreenRuntimeTestNoCooldown = false,
            GreenRuntimeTestIgnoreResourceAdmission = false, GreenRuntimeTestStillApplyCosts = true,
            GreenRuntimeTestAllowCastAtMaxFatigue = false,
            GreenRuntimeTestAllowCastAtZeroEndurance = false,
            GreenRapidCastRandomDirectionEnabled = true, GreenRapidCastWindowMs = 1000,
            GreenPreLockCruiseSpeedTilesPerSecond = 2.0,
            GreenTargetLostMinimumSpeedTilesPerSecond = 2.0,
            GreenLockedMaxSpeedTilesPerSecond = 12.0, GreenAccelerationTimeToMaxSeconds = 4.5,
            GreenAnyValidCollisionDetonationEnabled = true,
            GreenCollisionCharactersEnabled = true, GreenCollisionWorldSolidsEnabled = true,
            GreenCollisionVehiclesEnabled = true,
            GreenKnockdownRadiusTiles = 7.0, RedCraftHealthCostPoints = 3,
            RedCraftUnhappinessReductionPoints = 10, RedStarterItemCount = 8,
            PurpleMinimumCooldownDays = 1, PurpleBaseCooldownDays = 1,
        },
        CUSTOM = {
            GreenMaximumConcurrentCastsPerPlayer = 20, GreenMaximumConcurrentCastsGlobal = 40,
            GreenLethalRadiusTiles = 3.5, GreenKnockdownRadiusTiles = 7.0,
            GreenRuntimeTestModeEnabled = false, GreenRuntimeTestNoCooldown = false,
            GreenRuntimeTestIgnoreResourceAdmission = false, GreenRuntimeTestStillApplyCosts = true,
            GreenRuntimeTestAllowCastAtMaxFatigue = false,
            GreenRuntimeTestAllowCastAtZeroEndurance = false,
            GreenRapidCastRandomDirectionEnabled = true, GreenRapidCastWindowMs = 1000,
            GreenGuidanceTurnLevel = 4, GreenGuidanceTurnDegreesPerSecond = 150,
            GreenPreLockCruiseSpeedTilesPerSecond = 2.0,
            GreenTargetLostMinimumSpeedTilesPerSecond = 2.0,
            GreenLockedMaxSpeedTilesPerSecond = 12.0, GreenAccelerationTimeToMaxSeconds = 4.5,
            GreenAnyValidCollisionDetonationEnabled = true,
            GreenCollisionCharactersEnabled = true, GreenCollisionWorldSolidsEnabled = true,
            GreenCollisionVehiclesEnabled = true,
        },
    },
}

XNP_PZ_DistanceRunner.SandboxSchema = Schema
return Schema
